### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [DarlingSh1337/http-geminy#1]
internal/fs/utils.js:525
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
Im use cloud shell

**Comment by DarlingSh1337** [comment]
Hi you need to enter all the process.argv[] needed on script see the READ ME on the github

node http-geminy.js https://www.zataz.com/ http.txt 90 GET PHPSESSID:tisv10jeevnd5k7lrbt1a5h4l7

**Comment by ghost** [comment]
> node http-geminy.js https://www.zataz.com/ http.txt 90 GET PHPSESSID:tisv10jeevnd5k7lrbt1a5h4l7

ahaha really thanks <3

**Comment by DarlingSh1337** [comment]
nno problemes im here to help you :)

**Comment by PaltalkDDOS** [comment]
hi bro 
**51.81.42.176   port 5024**  <=== can someone hit ?
**ec2-3-217-24-157.compute-1.amazonaws.com  PORT  21012**  < === can someone hit ?
